version: 2
updates:
- package-ecosystem: pip
  directory: "/requirements"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 5
  labels:
  - product/invisible
- package-ecosystem: yarn
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 5
  labels:
  - product/invisible
  - dependencies/javascript
