version: '2.3'

services:
  formplayer:
    extends:
      file: "${COMPOSE_BASE}"
      service: formplayer
    links:
      - postgres
      - redis
    expose:
      - 8080
    ports:
      - "8080:8080"
      - "8081:8081"

  postgres:
    extends:
      file: "${COMPOSE_BASE}"
      service: postgres
    ports:
      - "5432:5432"

  couch:
    extends:
      file: "${COMPOSE_BASE}"
      service: couch
    command: ["--with-haproxy", "--with-admin-party-please", "-n", "1"]
    ports:
      - "5984:5984"

  redis:
    extends:
      file: "${COMPOSE_BASE}"
      service: redis
    ports:
      - "6379:6379"

  elasticsearch2:
    extends:
      file: "${COMPOSE_BASE}"
      service: elasticsearch2
    command: elasticsearch --cluster.name=${ES_CLUSTER_NAME}
    environment:
      ES_CLUSTER_NAME: ES_CLUSTER_NAME
      ES_JAVA_OPTS: "-Des.script.engine.groovy.inline.aggs=true -Des.script.engine.groovy.inline.search=true"
    ports:
      - "9200:9200"

  elasticsearch5:
    extends:
      file: "${COMPOSE_BASE}"
      service: elasticsearch5
    command: elasticsearch
    environment:
      ES_CLUSTER_NAME: ${ES_CLUSTER_NAME}
      ES_JAVA_OPTS: "-Xms750m -Xmx750m -Des.script.engine.groovy.inline.aggs=true -Des.script.engine.groovy.inline.search=true"
    ports:
      - "9205:9200"

  kafka:
    extends:
      file: "${COMPOSE_BASE}"
      service: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
    ports:
      - "9092:9092"

  zookeeper:
    extends:
      file: "${COMPOSE_BASE}"
      service: zookeeper
    ports:
      - "2181:2181"

  minio:
    extends:
      file: "${COMPOSE_BASE}"
      service: minio
    ports:
      - "9980:9980"
