name: commcare-hq migrations check
on:
  pull_request:
    branches:
    - master
    - hotfix-deploy
jobs:
  check_migrations:
    name: Check migrations
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Verify up-to-date migrations lockfile
      run: |
        make migrations
        git diff --exit-code migrations.lock
