name: commcare-hq tests
on:
  pull_request:
    branches:
    - master
jobs:
  tests:
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    strategy:
      matrix:
        include:
        - {TEST: python, NOSE_DIVIDED_WE_RUN: '05'}
        - {TEST: python, NOSE_DIVIDED_WE_RUN: '6a'}
        - {TEST: python, NOSE_DIVIDED_WE_RUN: 'bf'}
        - {TEST: python-sharded-and-javascript}
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      REUSE_DB: true  # do not drop databases on completion to save time
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Docker info
      run: |
        docker version
        docker-compose version
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Run tests
      env:
        TEST: ${{ matrix.TEST }}
        NOSE_DIVIDED_WE_RUN: ${{ matrix.NOSE_DIVIDED_WE_RUN }}
        JS_SETUP: yes
      run: scripts/docker test --noinput --stop --verbosity=2 --divide-depth=1 --with-timing --with-flaky --threshold=10 --max-test-time=29
    - name: Stop containers
      if: always()
      run: scripts/docker down
